### ISSUE TITLE
Create a tool to allow users to perform side-by-side analysis of vendor results

### ISSUE THREAD

**Issue by ghost** [mitre-attack/attack-evals#18]
Users need to have a way to more easily compare and contrast multiple vendor results.

UPDATE: A vendor side-by-side comparison tool is being developed. Initial release has been withdrawn and further delayed to resolve issues within the results display.

**Comment by connormagee** [comment]
UPDATE: A vendor side-by-side comparison tool is being developed. Initial release has been withdrawn and further delayed to resolve issues within the results display.

**Comment by JeffJLi** [comment]
This feature was included in the re-release of the ATT&CK Evalulations website at [https://attackevals.mitre-engenuity.org](https://attackevals.mitre-engenuity.org.) The vendor comparison tool can be found at [https://attackevals.mitre-engenuity.org/vendor_comparison.html](https://attackevals.mitre-engenuity.org/vendor_comparison.html).
