### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by shdaowclone** [mitre-attack/attack-evals#25]
links related to Carbon Black's attackevals.
https://attackevals.mitre.org/APT3/results/carbonblack/
images links gives XML error
https://d1zq5d3dtjfcoj.cloudfront.net/CB-10.A.2-2.png
(This XML file does not appear to have any style information associated with it.)
and links from the right panel that links to TTP gives 404 error
https://attackevals.mitre.org/APT3/results/CarbonBlack/scheduledtask

**Comment by JeffJLi** [comment]
We are still in the process of fixing the images, but the broken links from the Operational Flow (the right panel) have been fixed. We will post an update as soon as those images are restored. Thanks for letting us know, @shdaowclone!

**Comment by JeffJLi** [comment]
FIXED: The images cited in this issue were missing from CloudFront, but have been fixed/added as of the APT29 release on 04/21/2020.
