### ISSUE TITLE
technique comparison tool for AT29 shows different/wrong results

### ISSUE THREAD

**Issue by emeierg** [mitre-attack/attack-evals#27]
Compare test like this:
![image](https://user-images.githubusercontent.com/44072982/79918212-ce94e980-83e0-11ea-8561-f2c29190657f.png)

with results reported here:
https://attackevals.mitre.org/APT29/results/bitdefender/
https://attackevals.mitre.org/APT29/results/vmware/

Also when you mouse-over the pop-up icon for show configuration it shows a different vendor.
![image](https://user-images.githubusercontent.com/44072982/79918369-1e73b080-83e1-11ea-800a-138c5884408b.png)

Data is all over the place and nothing shown in that tool is reliable. Please fix that.

When it works this is a helpful tool although the reports with options to filter are great too.

Thank you.

**Comment by isaisabel** [comment]
I'm actually transferring the issue to the evals issue tracker just so that it shows up in the right place for posterity.

**Comment by JeffJLi** [comment]
FIXED: This bug was patched on April 22, 2020.
