### ISSUE TITLE
Technique Comparison Query links incorrectly loading 

### ISSUE THREAD

**Issue by stran-gh** [mitre-attack/attack-evals#29]
Being on the Technique Comparison Tool (for example, https://attackevals.mitre.org/technique_comparison.html?round=APT29&step_tid=1.B.1_T1059) and selecting a number of vendors, it becomes a convenient tool to compare different vendor results and share the final link with someone.

For example, by selecting Kaspersky, Blackberry Cylance, and VMWare Carbon Black I get a link : [https://attackevals.mitre.org/technique_comparison.html?round=APT29&step_tid=1.B.1_T1059&vendors=Kaspersky,BlackBerry%20Cylance,VMware%20Carbon%20Black](https://attackevals.mitre.org/technique_comparison.html?round=APT29&step_tid=1.B.1_T1059&vendors=Kaspersky,BlackBerry%20Cylance,VMware%20Carbon%20Black)
 
Unfortunately, if you copy-paste this link to a browser, the website returns the corrupted selection: https://attackevals.mitre.org/technique_comparison.html?round=APT29&step_tid=1.B.1_T1059&vendors=Kaspersky,Bitdefender,Bitdefender

It looks like every entry (vendor) which contains space symbol  “ ” (%20), is defaulted to Bitdefender.

**Comment by JeffJLi** [comment]
FIXED: This bug has been fixed as of 6/19/2020. See [this commit](https://github.com/mitre-attack/attack-evals/commit/1380e56eb438e990e87c0a424532e5b9264638c6).
