### ISSUE TITLE
404 - Adversary Emulation Summary page

### ISSUE THREAD

**Issue by juushya** [mitre-attack/attack-evals#32]
Looks like the link is broken -

ATT&CK Evaluations Adversary Emulation Summary
https://attackevals.mitre.org/methodology/
![image](https://user-images.githubusercontent.com/4639200/107919781-db975080-6f91-11eb-8bed-68c2e2ad2b70.png)

**Comment by JeffJLi** [comment]
Hi juushya, 

Thanks for the heads up! The ATT&CK Evaluations website has moved to [https://attackevals.mitre-engenuity.org](https://attackevals.mitre-engenuity.org). The specific page that you're looking for, which summarized the adversary emulation approach, can be found here: [https://attackevals.mitre-engenuity.org/adversary-emulation.html](https://attackevals.mitre-engenuity.org/adversary-emulation.html).

Please let us know if that solves your issue and if there's anything else we can do to help.

EDIT: It looks like your screenshot of the broken link is from the ATT&CK Website (not the ATT&CK Evaluations Website). I'll forward this information to the right people to get that fixed.

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
