### ISSUE TITLE
404 - link to SANS presentation

### ISSUE THREAD

**Issue by juushya** [mitre-attack/attack-evals#33]
The link to SANS presentation - Do-It-Yourself ATT&CK Evaluations to Improve Your Security Posture Presentation - needs to be updated.
![image](https://user-images.githubusercontent.com/4639200/107920441-fe763480-6f92-11eb-8ce7-79e057e9b1ec.png)

Old url (404):
https://www.sans.org/cyber-security-summit/archives/file/summit_archive_1559672321.pdf

The new url is (SANS account login required):
http://www.sans.org/cyber-security-summit/archives/download/22695

Thanks.

**Comment by JeffJLi** [comment]
This link is also on the ATT&CK Website (not the ATT&CK Evaluations Website). I'll get this information to the right people so that the link can be fixed. Thanks for the heads up!

**Comment by luizleite-hotmart** [comment]
the link is broken again but now could be found at 
https://www.sans.org/presentations/do-it-yourself-att-ck-evaluations-to-improve-your-security-posture/

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
