### ISSUE TITLE
LInk for APT 29 operational flow not available

### ISSUE THREAD

**Issue by iarakel2301** [mitre-attack/attack-evals#34]
https://attackevals.mitre-engenuity.org/APT29/operational-flow

**Comment by iarakel2301** [comment]
https://github.com/center-for-threat-informed-defense/adversary_emulation_library/blob/master/apt29/Operations_Flow.md

Got it here.

Thanks

**Comment by JeffJLi** [comment]
Hi iarakel2301,

We recently updated our website, so the APT29 Operational Flow page has moved to [https://attackevals.mitre-engenuity.org/enterprise/APT29/operational-flow.html](https://attackevals.mitre-engenuity.org/enterprise/APT29/operational-flow.html). We're also on a new Github repo: [https://github.com/attackevals/website](https://github.com/attackevals/website). Please go there for our latest updates and to get the fastest responses to issues.

Thanks!

**Comment by iarakel2301** [comment]
Hi Jeff,

Thank for the update.
Appreciate it.

Regards,
Ian Leroy Arakel
