### ISSUE TITLE
404 error: product eval results of APT29 attacks link fails

### ISSUE THREAD

**Issue by igolem** [mitre-attack/attack-evals#35]
The following link for the results of your testing gets a HTTP 404 error when clicked:
https://attackevals.mitre.org/evaluations.html?round=APT29

The link is provided by MITRE on this page:
https://www.mitre.org/news/press-releases/mitre-releases-results-of-evaluations-of-21-cybersecurity-products

**Comment by igolem** [comment]
Note that the "updated" link you provided also fails:
https://attackevals.mitre-engenuity.org/enterprise/evaluations.html?round=APT29

**Comment by JeffJLi** [comment]
Hi Jason,

Sorry for the inconvenience! The analogous page to the link you provided is [https://attackevals.mitre-engenuity.org/enterprise/participants/?rounds=apt29](https://attackevals.mitre-engenuity.org/enterprise/participants/?rounds=apt29). 

We recently updated our website (last week) and we're also in the process of retiring this Github repository in favor of our new repository at [https://github.com/attackevals/website](https://github.com/attackevals/website). Please direct future concerns there to get the fastest responses to issues.

Hope that helps!

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
