### ISSUE TITLE
https://attackevals.mitre.org/methodology/round2/detection-categories.html 404

### ISSUE THREAD

**Issue by garycart** [mitre-attack/attack-evals#36]
https://attackevals.mitre.org/methodology/round2/detection-categories.html which is a link from the guide gives a 404

**Comment by JeffJLi** [comment]
Hi garycart,

Our website has moved to a new domain, but [here's the new version](https://attackevals.mitre-engenuity.org/enterprise/apt29/detection-categories) of the page you're looking for. I've also noted that the guide needs to be updated.

Thanks!
