### ISSUE TITLE
Is anybody capable of assisting me in the reading or guide me to a webpage that helps me identify the various significances of these diverse results of my debugging execution from my phone's application please much gratitude in advance your assistance is appreciated so greatly!

### ISSUE THREAD

**Issue by IAMLegEndIAM** [mitre-attack/attack-evals#41]
-[00000000:0:0]plg.trace.generic.EndPoint
	-[00000000:1:0]plg.trace.generic.ArpCache
		-[00010000:2:0]plg.trace.generic.VendorByMac
		-[00010000:2:1]plg.trace.generic.TcpPort
			-[00030001:3:0]plg.trace.generic.HttpService
				-[00060001:4:0]plg.trace.generic.HnapService
				-[00060001:4:1]plg.trace.netgear.SoapService
				-[00060001:4:2]plg.probe.allegro.MisfortuneCookie
				-[00060001:4:3]plg.probe.allegro.Rom0Disclosure
				-[00060001:4:4]plg.probe.mikrotik.ChimayRed
				-[00060001:4:5]plg.probe.seagate.NasPhpInjection
				-[00060001:4:6]plg.probe.cisco.LinksysESeriesRce
				-[00060001:4:7]plg.trace.qnap.AuthLoginCgi
					-[000A0008:5:0]plg.probe.qnap.PhotoStationLfi
					-[000A0008:5:1]plg.probe.qnap.SurvStationSbo
				-[00060001:4:8]plg.probe.tplink.TdpServerRce
				-[00060001:4:9]plg.trace.terramaster.TosByVersion
					-[000A000A:5:0]plg.probe.terramaster.TosMultiVulnLt4206
				-[00060001:4:10]plg.trace.netgear.CurrentSettingHtm
					-[000A000B:5:0]plg.probe.netgear.StackOverflowByVer
					-[000A000B:5:1]plg.probe.netgear.R7000PreAuthRceByVer
				-[00060001:4:11]plg.probe.netgear.Dgn2200v1AuthByPass
				-[00060001:4:12]plg.probe.wd.MyBookLiveByVer
				-[00060001:4:13]plg.probe.tplink.ReUserAgentRce
				-[00060001:4:14]plg.probe.generic.HttpPathTrav
				-[00060001:4:15]plg.trace.binatone.HubbleConnected
				-[00060001:4:16]plg.probe.dlink.Dap2020HwAxFwLt101Multi
				-[00060001:4:17]plg.trace.dahua.Rpc2Login
					-[000A0012:5:0]plg.probe.dahua.Rpc2LoginBypass
			-[00030001:3:1]plg.trace.generic.SmbService
				-[00060002:4:0]plg.probe.microsoft.EternalBlue
				-[00060002:4:1]plg.probe.microsoft.DoublePulsar
			-[00030001:3:2]plg.trace.generic.TelnetService
				-[00060003:4:0]plg.probe.qualcomm.LbdDbgRedirect
			-[00030001:3:3]plg.probe.tcl.AndroidTvFs
			-[00030001:3:4]plg.trace.generic.RtspService
			-[00030001:3:5]plg.trace.generic.DceRpcService
				-[00060006:4:0]plg.probe.microsoft.PrintNightmare
		-[00010000:2:2]plg.trace.asus.InfosrvService
			-[00030002:3:0]plg.probe.asus.InfosrvBackdoor
		-[00010000:2:3]plg.trace.generic.SnmpSysDescr
			-[00030003:3:0]plg.trace.generic.SnmpStringbleed
				-[00060003:4:0]plg.probe.multi.Stringbleed
			-[00030003:3:1]plg.trace.cisco.DevInfoBySnmp
				-[00060004:4:0]plg.probe.cisco.RvSeriesUpnpFlaw
		-[00010000:2:4]plg.trace.generic.NbNameService
		-[00010000:2:5]plg.trace.generic.UpnpService
			-[00030005:3:0]plg.probe.generic.CallStranger
		-[00010000:2:6]plg.trace.generic.MdnsService
	-[00000000:1:1]plg.trace.generic.NsConfig
		-[00010001:2:0]plg.trace.external.NsLookup
			-[00030001:3:0]plg.trace.external.IpLookup
				-[00060001:4:0]plg.probe.generic.NsDiff
				-[00060001:4:1]plg.probe.external.BlacklistByDns
			-[00030001:3:1]plg.probe.external.BlacklistByDns
	-[00000000:1:2]plg.trace.external.IpLookup
		-[00010002:2:0]plg.probe.generic.NsDiff
		-[00010002:2:1]plg.probe.external.BlacklistByDns

**Comment by IAMLegEndIAM** [comment]
Commenting for later on

**Comment by jondricek** [comment]
Admin note: closing all remaining issues and pull requests prior to archiving the repository
