### ISSUE TITLE
Crowdstrike Results / Broken link in 12.F.1 Discovery, Permissions Group Discovery

### ISSUE THREAD

**Issue by samsson** [mitre-attack/attack-evals#5]
In Operational Flow side panel.

12.F.1 Discovery
Permissions Group Discovery
Link to: 
https://attackevals.mitre.org/evaluations/crowdstrike.1.apt3.1/procedures/permissionsgroupdiscovery

Errors: 404

**Comment by samsson** [comment]
Same issue with some other links:
13.C.1 
https://attackevals.mitre.org/evaluations/crowdstrike.1.apt3.1/procedures/queryingtheregistry

**Comment by jburns12** [comment]
Thanks for the heads up, @samsson! We'll address these problems and close the issue once they're merged into the site.

**Comment by JeffJLi** [comment]
FIXED: The broken links for step 12.F.1 and step 13.C.1 have been fixed. Thanks again for notifying us about this, @samsson!
